# FOSUserBundle Configuration. It is used for automating authentication
# and registration of our users.
fos_user:
    db_driver: orm # Use Doctrine ORM
    firewall_name: main
    user_class: App\Entity\User\User
    from_email:
        address: swiftmailer.username
        sender_name: swiftmailer.username
    group:
        group_class: App\Entity\User\Group