sonata_user:
    class:
        user: App\Entity\User\User
        group: App\Entity\User\Group

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~